version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5080:80/tcp"
    environment:
      TZ: 'Europe/Brussels'
      WEBPASSWORD: 'papier22'
    volumes:
      - '/docker/etc-pihole:/etc/pihole'
      - '/docker/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
