version: "3.9"

services:
  core:
    image: containrrr/watchtower:latest
    restart: always
    environment:
      - TZ="Europe/Brussels"
      - WATCHTOWER_POLL_INTERVAL=${POLL_INTERVAL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
