version: "3.9"

networks:
  watchtower-networks:
    name: watchtower-net

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower-core
    restart: always
    environment:
      - TZ="Europe/Brussels"
      - WATCHTOWER_POLL_INTERVAL=${POLL_INTERVAL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - watchtower-networks
