version: "3.9"

services:
  watchtower:
    image: containrrr/watchtower:latest
    name: core
    restart: always
    environment:
      - TZ: "UTC"
      - WATCHTOWER_POLL_INTERVAL=${POLL_INTERVAL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
