version: "3.9"

networks:
  crafty-network:
    name: crafty-net
  
services:
  crafty:
    container_name: crafty-core
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Europe/Brussels
    ports:
      - "8000:8000"
      - "8443:8443"
      - "25565:25565"
    volumes:
      - /docker/crafty/backups:/crafty/backups
      - /docker/crafty/logs:/crafty/logs
      - /docker/crafty/servers:/crafty/servers
      - /docker/crafty/app/config:/crafty/app/config
      - /docker/crafty/import:/crafty/import
    networks:
      - crafty-network
