version: "3.9"

services:
  crafty:
    container_name: crafty-core
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Europe/Brussels
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8123:8123"
      - "19132:19132/udp"
      - "25500-25600:25500-25600"
    volumes:
      - /docker/crafty/backups:/crafty/backups
      - /docker/crafty/logs:/crafty/logs
      - /docker/crafty/servers:/crafty/servers
      - /docker/crafty/app/config:/crafty/app/config
      - /docker/crafty/import:/crafty/import
