version: "3.9"

volumes:
  crafy-data:
    driver: local
    
services:
  crafty:
    container_name: crafty-core
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8123:8123"
      - "19132:19132/udp"
      - "25500-25600:25500-25600"
    volumes:
      - crafy-data/backups:/crafty/backups
      - crafy-datay/logs:/crafty/logs
      - crafy-data/servers:/crafty/servers
      - crafy-data/config:/crafty/app/config
      - crafy-data/import:/crafty/import
