version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  site1:
    image: "traefik/whoami"
    container_name: "simple-service-1"
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site1.rule=Host(`site1.home.io`)"
      - "traefik.http.routers.site1.entrypoints=web"
      
  site2:
    image: "traefik/whoami"
    container_name: "simple-service-2"
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site2.rule=Host(`site2.home.io`)"
      - "traefik.http.routers.site2.entrypoints=web"
