version: "3.9"

services:
  httpd:
    image: httpd:latest
    container_name: web-public-1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bridger

networkd:
  - bridger
