version: "3.9"

services:
  httpd:
    image: httpd:latest
    container_name: web-public
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/website:/usr/local/apache2/htdocs
    network_mode: "bridge"
